spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

api:
  kakao:
    blog-url: 'https://dapi.kakao.com/v2/search/blog'
    token: '52f9fd99a0bf6b2192f9a9e3493cbc03'
  naver:
    blog-url: 'https://openapi.naver.com/v1/search/blog.json'
    client-id: 'l65pXETUhz_qQnG6Jyjg'
    client-secret: 'PNy18BOwci'

mq:
  host: localhost
  port: 5672
  virtual-host: /
  username: guest
  password: guest
  exchange: blog
  queue-keyword: keyword
